### ISSUE TITLE
add note about 'end date'?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ox-it/ords#163]
```
to explain what it will be used for, and to reassure that their database won't 
be deleted after the end date


```

Original issue reported on code.google.com by `Charlie....@gmail.com` on 1 Aug 2013 at 8:25

**Comment by MerielP** [comment]
This is now covered in the documentation (and has been for some time) - it's explicitly stated that you'll be able to carry on using the ORDS after the stated end date if you need to (and also that you can change the end date if the project is extended). 

The help text by the 'End date' field in the Create New Project form says 'The actual or anticipated end date of the project', which hopefully also indicates that it's not a hard limit.

Is that sufficient? I'm wary of adding any further help text to the Create New Project form itself, as there's already quite a lot there.

**Comment by jajwilson** [comment]
This'll do fine.
