### ISSUE TITLE
'Query data using query builder' button on Dataset List page goes to old version of query builder

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#715]
To reproduce, go to the Dataset List page for an ORDS database version. Click 'Query data using query builder'. Note that you're taken to the old, inferior version of the query builder, rather than the new one which can be reached via the View, Edit, and Query Data page.

**Comment by scottbw** [comment]
Fixed - also found another link (unused I think) on table.jsp to updated both to new VQD page.

**Comment by MerielP** [comment]
Great - thanks!
