### ISSUE TITLE
Schema designer not showing tables etc.

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#716]
To reproduce, try to view a database structure in the Dev version of ORDS. The gridded background appears, but not the tables, relationships, or the toolbar. This is happening for me in both Chrome and Firefox.

**Comment by thestoat** [comment]
I suspect this would be one for Scott ...

**Comment by scottbw** [comment]
This is caused by bug #720

**Comment by thestoat** [comment]
This should now be ok

**Comment by scottbw** [comment]
Fixed as result of closing #720
