### ISSUE TITLE
All REST APIs are broken

### ISSUE THREAD

**Issue by scottbw** [ox-it/ords#720]
None of them work since branch merged in; this affects the Schema Designer and the Query Builder.

Looks like the base constructors were modified, which breaks all the annotated classes as Jersey can't instantiate them anymore.

**Comment by scottbw** [comment]
HINT: you get the user principle from the SecurityContext rather than code them into the constructor...

**Comment by thestoat** [comment]
This should now be fixed. Please check and let me know ...

**Comment by scottbw** [comment]
It didn't build - the unit tests in Project Node didn't pass.

**Comment by thestoat** [comment]
Sorry - should be ok now.

**Comment by scottbw** [comment]
Yay! All working again on Dev
