### ISSUE TITLE
Schema designer still behaving strangely after ODBC changes

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#721]
Since issue #720 was fixed I can view the schema designer, but it's not working as it should be...
1) If I try to exit the designer I get a 'I you sure you want to exit? Any unsaved changes will be lost' message, even though I haven't edited anything. Click 'OK' does not have any effect - I'm still stuck in the designer.
2) The Mondial db structure is either not displaying correctly or has not been interpreted correctly during the upload process. The three tables are all there, as are the fields, but the relationship between the province table and the country table has been lost. province.ID should connect to country.Code.

Scott, pass this over to Dave if it's still related to the ODBC changes rather than your own new upload code.

**Comment by jajwilson** [comment]
Oh. And clicking 'revert changes' just seems to remove the entire structure and bring up a 'no schema to show!' message. I can exit the designer once I've reverted the schema to nothing, but that's not much use.

**Comment by scottbw** [comment]
I get really weird results.

The first time I tried, I got "no schema to show". Then I got the schema, but no tables showed up in the query builder - the REST result was an empty table list. Something has really gone wrong in the REST code. It shouldn't be anything related to the upload code as that only affected Access database uploads and this affects SQL dumps and CSV imports.

**Comment by jajwilson** [comment]
Ok. I'll add Dave to see if he's got any idea what might be causing this.

**Comment by thestoat** [comment]
Can you try now. I did find some funnies but have fixed those. Let me know ...

**Comment by jajwilson** [comment]
Yep, seems to work again.
