### ISSUE TITLE
ODBC retrospective data access required

### ISSUE THREAD

**Issue by thestoat** [ox-it/ords#722]
With the advent of ODBC support, there is a requirement to allow the new ORDS code to access data that was created prior to the code being introduced.

Originally, ORDS used a Postgres role (typically called ords) for all data access.
With the new ODBC-enabled code, ORDS now uses a different role per user to access their data. Those roles are created on data upload (if they don't already exist) and, when a user creates a database, the relevant permissions are assigned.

Obviously that will cause problems with data already uploaded, since the ORDS users and relevant permissions won't exist.

Judging by the scale of the problem I think it is better to have the permissions assigned programatically rather than by hand. There are around 150 databases on one of the app database servers (I don't have access to the other).

My questimate is 2 days effort for this.

**Comment by jajwilson** [comment]
That sounds reasonable to me. I think that trying to reconnect every project on the App server by hand would lead to suicidal thoughts. We need to make sure we’ve sorted every critical bug on Dev first though. I’ve got lots of meetings today, but will try to check the latest reported fixes as some point this afternoon.

James

**Comment by thestoat** [comment]
I shall start looking at this now anyway in anticipation since I don't think any more critical issues exist. Feel free to promote issues if needed though.

**Comment by thestoat** [comment]
This should now be ok.
