### ISSUE TITLE
Database names being misreported in ODBC connection string lists

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#724]
1. Ensure your project has 'enable ODBC access' ticked, and contains more than one database (such as 'New test project especially for Dave' in Dev.
2. Go to your accounts screen to find ODBC string.
3. Notice that the same database name is given twice, but with different ODBC names

I'm not sure why only the most recent db is being listed, nor why two different strings are being given - I would expect all three databases in the project to be listed, with a separate connection string for each.

**Comment by thestoat** [comment]
Your expectation is correct.

**Comment by thestoat** [comment]
Fixed

**Comment by jajwilson** [comment]
Hmm. Doesn't seem to be fixed when I try. 
![misreporteddbnames](https://cloud.githubusercontent.com/assets/11886974/10394577/10ebc42c-6e90-11e5-8823-1838136a81e5.png)
As you can see, by the 'New test project especially for Dave' project, two databases are listed. Both are called 'Mondial #3 uploaded on the 8th October'. Neither is actually the db named. The first one is in fact 'Good old Mondial', whilst the second is 'Mondial #2 uploaded after fixes on 7th October' the third db in the project - the one that is actually called 'Mondial #3 uploaded on the 8th October' is not appearing in the list. Could you take another look?

**Comment by thestoat** [comment]
Sorry - I should have said, this is only fixed for new databases added. This is because there was a problem at the database level so the web site is reporting the status accurately.

**Comment by jajwilson** [comment]
Ok. When we shuffle all of this code over into App, will the same problem persist? i.e. will people only be able to create a ODBC link automatically for new projects/database that they add after that point?

**Comment by thestoat** [comment]
Currently ODBC connections have been done by hand and those settings should continue to work. This was just a reporting issue. Users of app shouldn't be affected since currently the information isn't reported anyway.

**Comment by jajwilson** [comment]
Yep - works now with new projects.
