### ISSUE TITLE
Can't create new projects

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#727]
At present it is not possible to create a new project in Dev. Clicking the 'new project' button gives me the following stacktrace error:

HTTP Status 500 - Unable to compile class for JSP: An error occurred at line: 6 in the jsp file: /includes/projectForm.jsp Project cannot be resolved to a type 3: String SELECTED = "selected=\"selected\""; 4: String CHECKED = "checked=\"checked\""; 5: 6: Project project = (Project) session.getAttribute("projectData"); 7: String name = ""; 8: String description = ""; 9: String startDate = ""; An error occurred at line: 6 in the jsp file: /includes/projectForm.jsp Project cannot be resolved to a type 3: String SELECTED = "selected=\"selected\""; 4: String CHECKED = "checked=\"checked\""; 5: 6: Project project = (Project) session.getAttribute("projectData"); 7: String name = ""; 8: String description = ""; 9: String startDate = ""; Stacktrace:

type Exception report

message Unable to compile class for JSP: An error occurred at line: 6 in the jsp file: /includes/projectForm.jsp Project cannot be resolved to a type 3: String SELECTED = "selected=\"selected\""; 4: String CHECKED = "checked=\"checked\""; 5: 6: Project project = (Project) session.getAttribute("projectData"); 7: String name = ""; 8: String description = ""; 9: String startDate = ""; An error occurred at line: 6 in the jsp file: /includes/projectForm.jsp Project cannot be resolved to a type 3: String SELECTED = "selected=\"selected\""; 4: String CHECKED = "checked=\"checked\""; 5: 6: Project project = (Project) session.getAttribute("projectData"); 7: String name = ""; 8: String description = ""; 9: String startDate = ""; Stacktrace:

description The server encountered an internal error (Unable to compile class for JSP: An error occurred at line: 6 in the jsp file: /includes/projectForm.jsp Project cannot be resolved to a type 3: String SELECTED = "selected=\"selected\""; 4: String CHECKED = "checked=\"checked\""; 5: 6: Project project = (Project) session.getAttribute("projectData"); 7: String name = ""; 8: String description = ""; 9: String startDate = ""; An error occurred at line: 6 in the jsp file: /includes/projectForm.jsp Project cannot be resolved to a type 3: String SELECTED = "selected=\"selected\""; 4: String CHECKED = "checked=\"checked\""; 5: 6: Project project = (Project) session.getAttribute("projectData"); 7: String name = ""; 8: String description = ""; 9: String startDate = ""; Stacktrace:) that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 6 in the jsp file: /includes/projectForm.jsp
Project cannot be resolved to a type
3:     String SELECTED = "selected=\"selected\"";
4:     String CHECKED = "checked=\"checked\"";
5: 
6:     Project project = (Project) session.getAttribute("projectData");
7:     String name = "";
8:     String description = "";
9:     String startDate = "";

An error occurred at line: 6 in the jsp file: /includes/projectForm.jsp
Project cannot be resolved to a type
3:     String SELECTED = "selected=\"selected\"";
4:     String CHECKED = "checked=\"checked\"";
5: 
6:     Project project = (Project) session.getAttribute("projectData");
7:     String name = "";
8:     String description = "";
9:     String startDate = "";

Stacktrace:
    org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
    org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:331)
    org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:469)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:378)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:353)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:340)
    org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:646)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.28 logs.

Apache Tomcat/7.0.28

**Comment by scottbw** [comment]
That was me being fat thumbed while deleting a ProjectBilling import. Should be OK now

**Comment by jajwilson** [comment]
Ok - I can now get to the 'Create New Project' form and fill it in, but on submission I'm getting the error message "Internal error creating project". There's nothing controversial in my project metadata.

**Comment by scottbw** [comment]
Yes - though it does create the project which is puzzling. Also I don't see the error message when I try this on a local build

**Comment by thestoat** [comment]
Ok - seems to be a server setup problem. I'll sort it

**Comment by thestoat** [comment]
I have raised issue 10078016 with sysdev to sort this out.

**Comment by thestoat** [comment]
Note that you won't get very far with ORDS until this is sorted - the problem is that credentials on the server are incorrect. Thus the project will get created (because that is a Hibernate thing  -no problems there) but no ODBC users are created on the project server (due to the invalid creds). Without these ODBC users, you won't be able to upload or change any data (unless your creds were created previously on the server).

**Comment by thestoat** [comment]
Should be ok now

**Comment by jajwilson** [comment]
Yep - seems fine now.
