### ISSUE TITLE
Filtering interface does not appear on tables with three or more linked tables

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#732]
In the editing interface, open a table which has three or more linked tables. Note that the 'Filter Results' heading is displayed, but not the actual filtering options. Apologies if its not the 3-or-more linked tables causing this, but that's the only consistent element that I've spotted where this bug occurs.

**Comment by thestoat** [comment]
Is it possible to add one of the offending databases here?

**Comment by jajwilson** [comment]
The db where I've spotted this is not to be publicly shared as yet (even though it's only got a small amount of data in it so far). I'll send it to you and Scott via Oxfile.

**Comment by jajwilson** [comment]
Sorry - not thinking clearly. Might as well just add you both as members of the version I've uploaded to Dev. The Database in question is in the project 'Standard Test'. It's called 'Resistance is futile 2', and the tables to look at are: tblrelationships and tblpersons.

Ah, it seems that you are already a member of this project Dave whilst Scott is 'pending'. I'll try removing you Scott and then adding you again so that you get a fresh invitation.

**Comment by scottbw** [comment]
My account on Dev doesn't seem to work properly - all the emails tell me I haven't registered yet ... but when I log in, I'm clearly there!

**Comment by jajwilson** [comment]
Dave - is there any way to reset Scott's account?

**Comment by thestoat** [comment]
I have just looked at every table in that database and I can see no problem. Filtering options are available in all. 

Scott - please forward to me one of the offending emails

**Comment by jajwilson** [comment]
That's odd. Here's a screenshot showing the lack of any filtering option for tblpersons:

![nofilteroptions](https://cloud.githubusercontent.com/assets/11886974/10610040/11c84148-773e-11e5-9da3-bfbb5cc2063b.png)

**Comment by thestoat** [comment]
It works ok for me on Firefox and Safari on Mac. It also works fine with Chrome and Firefox on Linux. Can you try with different browsers and paste your results.

**Comment by jajwilson** [comment]
How strange. Obvs I'm only using Windows 7, but here are the results on Firefox and IE...
Firefox:

![nofilteronfirefox](https://cloud.githubusercontent.com/assets/11886974/10613191/0f42040a-774c-11e5-9d92-095f8156bd99.png)

And IE:

![nofilterie](https://cloud.githubusercontent.com/assets/11886974/10613196/173ceb34-774c-11e5-821e-8cfa9555f57e.png)

**Comment by jajwilson** [comment]
Any idea why there is a 'null' message below the tables in addition to the lack of a filter?

**Comment by scottbw** [comment]
Can you open the Javascript console and see if there are any error messages there?

**Comment by jajwilson** [comment]
Aha, yet there is. I see:
"RedQueryBuilder-0.js:961 Uncaught java.sql.SQLException: In SELECT "x0".\* FROM "tblpersons" "x0" WHERE ("x0"."Notes" = ?) at 13 wanted identifier"

**Comment by scottbw** [comment]
Hmm ... this is an error you get in RQB when asking it to do wildcards against a single table ("x0".*). Which usually never happens as the code in the table view contains a workaround for it.

Is this a query or a table you're filtering?

**Comment by jajwilson** [comment]
I'm just in the table editing view - I can't filter anything as the filtering interface isn't being displayed. That's the mystery. I get the same error when I navigate to other tables with three or more related tables. I don't see any error in tables with two or fewer related tables.

**Comment by thestoat** [comment]
I got rid of the 'null' message.

**Comment by scottbw** [comment]
I've managed to narrow it down - I can replicate the bug - it occurs on tables which have multiple foreign keys targeting the _same_ foreign table. E.g. item.category = category.id and item.category2 = category.id.

**Comment by scottbw** [comment]
OK, its another label conflict. I can solve it by having the labels look like this:

"category (category1) ..."
"category (category2) ..."

... which is probably sensible anyway.

**Comment by scottbw** [comment]
OK, I've checked in a fix for this to try out.

**Comment by jajwilson** [comment]
Hmm. Still can't see the filter options for the 'Resistance if Futile 2' db, in the 'Standard Test' project - see tables tblpersons and tblrelationships. You should have access: https://dev.ords.ox.ac.uk/ordsProjectNode/database.jsp?dbProjectId=591697&lid=1254892

By the way, whilst you're at it could you rename the 'Filter Results' heading to 'Filter' - the form is grammatically ambiguous!

**Comment by scottbw** [comment]
For some reason I can't actually get to the tables in that db - it just redirects me to the front page

**Comment by scottbw** [comment]
Argh, the reason is we aren't seeing the fixed code running on DEV because Jenkins seems to be down. I can't see any jobs defined or running.

**Comment by jajwilson** [comment]
Great. Looks like its working.
