### ISSUE TITLE
Upload of sql dump to Dev does not complete

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#735]
It's been several days, and my SQL dump of the OxRep database (generated by the ORDS App) is still being reported as 'import in progress' in my project 'A new project founded on the 20th October 2015' on Dev. I'll share the SQL dump via OxFile.

**Comment by thestoat** [comment]
The reason for this is due to the file itself (other dump files upload fine). I think it is a valid file so the processing needs to alter to ensure sql upload works with all files.

**Comment by thestoat** [comment]
This should now be fixed, though note the related issue 738.
