### ISSUE TITLE
SQL export doesn't work

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#745]
To reproduce:
1. Attempt to export an SQL dump of a database
2. Open the exported file, and find it's empty (or view the file properties, and see it has a size of 0 bytes)

After a bit of experimentation, it looks as though this doesn't happen with absolutely all databases, but it does with quite a lot of them. I _think_ it may be another effect of the ODBC work - as I'm getting this problem repeatedly with older databases, but not with a recently uploaded one. CSV export appears unaffected.

**Comment by thestoat** [comment]
Should now be fixed

**Comment by MerielP** [comment]
I can now export SQL files that have a non-zero size and which look like they contain actual SQL, which is decidedly promising! 

However, to be on the safe side, I tried reuploading one of the new exports, and promptly ran into the issue I've noted in #746 (uploads of SQL imports not completing). I'll leave this issue open until I can check the exported files are working OK.

**Comment by thestoat** [comment]
Ok, I think the export now does work - the resulting file looks fine. However, importing does still have a problem so looking at that now ...

**Comment by thestoat** [comment]
This should now be ok (with the caveat that you need to use a "sensible" name for the file to upload rather than one with strange characters or spaces - that is the subject of a different issue). Please check and let me know

**Comment by MerielP** [comment]
Hurrah - now seems to work fine (and I can indeed reupload the file if I remove the spaces from the file name). Will resolve this issue.
