### ISSUE TITLE
Can't upload the SQL dump of the OxRep db

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#746]
I thought this had all been fixed - it seems that old bugs are reappearing.

When I create an sql dump of the App version of the OxRep project and then try to upload it into a project on Dev, the upload process appears to complete ok, but it seems there is no schema in the schema designers, and no tables to edit in the data editing view.

File too big to attach, so sending via OxFile

**Comment by scottbw** [comment]
Just tried on DEV and it works OK there.

**Comment by jajwilson** [comment]
Puzzling. I'll try again.

**Comment by jajwilson** [comment]
Nope. Can't get it to create a schema or tables either in an 'old' project, nor one I just created on Dev called 'A new test project 19th November 2015'. I'll add you to this so that you can see for yourself.

**Comment by scottbw** [comment]
I've also shared my "Project Banana" project on DEV with you where it did upload OK.

**Comment by jajwilson** [comment]
It's Schrodinger's bug

**Comment by scottbw** [comment]
It just hates you.

**Comment by jajwilson** [comment]
:-(

**Comment by thestoat** [comment]
Hands up who likes computers. 

I'll take a look shortly - nothing works for me so I am sure I'll see the problem. And me, with a pain down the left side of my diodes ...

**Comment by thestoat** [comment]
Well, there's a first. Works fine for me too. There was a problem with logging on dev4 that broke things for a while - can you try again. If the problem still happens, share the project with me and I'll look further ...

**Comment by jajwilson** [comment]
Gah! It's still not working for me! To whom must I sacrifice?!
I even tried downloading the SQL dump again in case my local file had somehow become corrupted. I've emptied my cache. Yet still the ORDS proudly announces that my upload was successful and the database contains 0 tables. The ORDS is really winding me up today.

You are both down as members of 'A new test project 19th November 2015'

**Comment by jajwilson** [comment]
Have tried both Chrome and Firefox browsers and with ODBC access switched on and off.

**Comment by jajwilson** [comment]
Oh hello. Now I'm having trouble loading a different database which I haven't had any problems with before. Is one of the servers getting full?

**Comment by MerielP** [comment]
I'm also having problems with SQL uploads. I don't even get as far as James does: the upload process just doesn't complete (my project page has been displaying a couple of 'Import in progress' messages for some time now...). So apparently it hates me even more than it hates James. :-(

This is in the project called 'Trial project' (I've added Dave as a member; Scott already was one), and the problematic databases are called 'Testing upload' and 'Another upload test'.

I did just manage to successfully upload an Access database, though - so it looks as though whatever the problem is may be SQL specific.

**Comment by thestoat** [comment]
Meriel - please append one of the problem databases so I can try this for myself

**Comment by MerielP** [comment]
Github won't let me attach an SQL file - I'll email it to you.

**Comment by thestoat** [comment]
Hi Meriel - could the problem you are seeing be due to the fact that you are using a trial project?

**Comment by jajwilson** [comment]
users should be able to upload dbs to trial projects. See https://sharepoint.nexus.ox.ac.uk/sites/itservices/ords/_layouts/WordViewer.aspx?id=/sites/itservices/ords/Shared%20Documents/ORDS%20Access%20and%20Account%20Maintenance%20Plan.docx&Source=https%3A%2F%2Fsharepoint.nexus.ox.ac.uk%2Fsites%2Fitservices%2Fords%2FSitePages%2FHome.aspx&DefaultItemOpen=1&DefaultItemOpen=1

**Comment by jajwilson** [comment]
Dave, if it help for diagnosis, at 1:55 today I uploaded an slq file to the 'Standard Test' project, 'Irish Surgeons 6' database. It failed as before, although it took much longer (almost 30 minutes) before sending me the happy and completely untrue 'Success!' email. I'm still having the same problems as yesterday - no tables in my uploaded dbs.

**Comment by MerielP** [comment]
I have successfully uploaded databases to trial projects in the past - and as James says, this is something users ought to be able to do.

I can see that you have uploaded one of the databases to the same project (ORDS helpfully sent me a message telling me this - which initially made me think the upload I tried earlier had finally completed). You seem to have got further than I did, but when I try to view that database (Dave test 1), I have the same problem that James has been experiencing - no tables visible either in the schema designer or on the View, Edit, and Query data page.

**Comment by thestoat** [comment]
Also, Meriel, please try again but renaming the file to Graveyards.sql (i.e. without the space), and uploading to a non trial project. Is all now ok? Just so that I know what to fix :-)

**Comment by thestoat** [comment]
Ah yes - the trial limits what can happen after the upload. I can now upload the db fine - Meriel, look at test 2 in your project to see that. I think I understand the problem - please check you can upload when the filename does not have spaces

**Comment by jajwilson** [comment]
I GOT IT TO WORK!

Doing a little jig in my office.

We're gradually chasing these bugs outta town.

But as I mentioned in a private email to Dave, when I tried uploading ‘surgeons_pg_dump_2015-11-19_2.sql’ over lunchtime, that didn't work, and it contained no spaces in the filename. I'll try that one again now...

**Comment by MerielP** [comment]
I've attempted upload of versions of the file with and without spaces in the name to trial and full projects.

Both versions without spaces seem to have worked fine - and I can also see Dave's second test upload. The versions with spaces still seem to be stuck mid import.

This is a change from what used to happen, as I've previously uploaded the very same files (with spaces in the name) without any problems.

**Comment by jajwilson** [comment]
It doesn't seem to be the '-' hyphens that are preventing db uploads. I just tried uploading 'surgeons_pg_dump_2015_11_19_2.sql', and that failed in the way described above.

**Comment by thestoat** [comment]
I plan to remove "strange" characters from filenames since I think this is causing the issues - not just spaces but others too (maybe a dash or plus). But before I do that I shall try file uploads by escaping the characters

**Comment by jajwilson** [comment]
Ah - looks like it was the database rather than the hyphens that were causing the problem. An older version of the same db just uploaded fine. Phew. So it seems that hyphens, numbers, and underscores are all off the hook.

**Comment by jajwilson** [comment]
Oh yeah, now I look at my sql dump its completely mangled. No wonder that one wasn't working.

**Comment by jajwilson** [comment]
Mind you - I shouldn't have been receiving a 'success' message in that instance. I'll add that as a different issue - but of high importance rather than critical.

**Comment by thestoat** [comment]
Are you now happy with this issue?

**Comment by jajwilson** [comment]
Yes. Fixed.
