### ISSUE TITLE
Uploading a mangled sql dump to ORDS results in a 'congratulations' email, even though the upload was a failure

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#748]
1. Try to upload a badly mangled sql dump to ORDS
2. Wait for a bit
3. Receive an email saying 'Congratulations! Your database (surgeonspg.sql) has been successfully imported into ORDS. You can now log in to ORDS and start using it'.
4. Find that your newly uploaded database now unreasonably has no tables in it.
5. Feel frustrated.

Instead the ORDS should recognize that a db that has uploaded without containing any tables is not a healthy database and give a 'Sorry, the ORDS could not upload your database x. Please contact ords@it.ox.ac.uk to diagnose the problem.' message.

**Comment by thestoat** [comment]
Should be fixed. If not, please add the problem file you are using.

**Comment by jajwilson** [comment]
Yes, that works, or rather it doesn't work but does so correctly.
