### ISSUE TITLE
Comments on fields are no longer displaying in editing interface

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#752]
When a comment is added to a field, a question mark symbol should appear next to the field name in the editing interface (hovering the mouse pointer over this displays the comment). The question mark is no longer there.

Comments on whole tables still seem to be working as they should.

**Comment by thestoat** [comment]
I assume you mean the database schema editing interface (rather than the data editing interface)? Can you supply a link of where the question mark does appear (table) and an example where it doean't (field name)? I am having problems finding any ...

**Comment by MerielP** [comment]
No - I mean the data editing interface. We've never had the question mark symbols in the schema designer.

On Dev, there's a project called 'Trial project' which contains a database called 'Example database'. In that, there's a table called 'table with comments'. This has comments on both the table itself, and on all of the fields except the primary key. If you go and view the table in the data editing interface ([this](https://dev.ords.ox.ac.uk/ordsProjectNode/table.jsp?dt=main&dbProjectId=627348&lid=922197&tn=table%20with%20comments) is the URL on my screen), you will see the comment ('A table which has comments on both it and the fields in it') at the bottom of the screen, but you will not see any question mark symbols on the field names, despite the fact that the schema designer clearly shows they do have comments.

By contrast, if you go to App, and look at 'Sample project', in the database called 'Victorian Gentlemen's Clubs', in the 'people' table ([this](https://app.ords.ox.ac.uk/ordsProjectNode/table.jsp?dt=main&dbProjectId=225101&lid=225522&tn=people) is the URL), you will see that the 'occupation' field name has the small question mark symbol next to it. 

![table with comment symbol](https://cloud.githubusercontent.com/assets/13660306/14613641/45118376-0595-11e6-8832-fea62c37daab.PNG)

Hovering over this displays the comment.

In the course of investigating this, I've also discovered another problem with comments: if a table contains no records, any comments are not displayed. (One wouldn't expect comments on individual fields to be displayed under these circumstances, but comments on the table should be.)

(I'm bumping the priority of this up from High to Critical, as this is currently working in App but not on Dev, and we don't want to do a new build to App until we're reasonably sure it's not going to break any existing features.)

**Comment by thestoat** [comment]
Fixed

**Comment by MerielP** [comment]
Excellent - thanks.

The problem where comments don't display on tables with no records is still there, but I've just checked and that also happens on App, so it doesn't count as critical. I'll close this issue.
