### ISSUE TITLE
List of ODBC details not showing 'main' database name

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#755]
This may be a browser thing, but it affects both Chrome and Firefox. In the list of log-in details I'm seeing this:

![ordsnomainodbc](https://cloud.githubusercontent.com/assets/11886974/12173496/00d33984-b54f-11e5-83a6-401184e3abcc.png)

The connection details listed for the 'Demographics' project include database names for the Mondial : milestone_3052_3050, the Mondial : test_3052_3050, and the ColoursTest : main_3789_3787. But they don't include the one that I want, which should read 'Mondial : main_3052_3050'. I can work this out, but most of our users will be confused.

**Comment by thestoat** [comment]
There are issues here. I'm looking ...

**Comment by thestoat** [comment]
Should now be fixed. You may see some artefacts with old entries - I can get rid of those by hand if they annoy you.

**Comment by jajwilson** [comment]
Yes, seems to work fine now.
