### ISSUE TITLE
Not clear to users how to find ODBC connection details after turning ODBC on for a project

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#756]
A user turns ODBC on via the 'Edit Project Details' page, but after saving the new status, they are taken back to the regular project page. It is not clear that they need to go to their 'account' page to actually find the newly issued ODBC details. Of course, they are also emailed a message instructing them to go to the correct page in order to create a new password, which will work (unless they hit #754), but it's not very obvious that they will need to copy and paste the details from here in the future.

Would it be possible to include the ODBC connection details for a given project on the Project page itself? This would seem to be rather more intuitive. It would also be good to add a link from just below the connection details to the relevant documentation (which we'll add in due course, as I'll need to tweak the existing documentation a little first).

**Comment by thestoat** [comment]
Good idea.

**Comment by jajwilson** [comment]
Yep - looks good.
