### ISSUE TITLE
Turning ODBC access to 'off' on a project doesn't actually prevent people connecting to that project via ODBC

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#757]
It seems that the 'switch ODBC off' function doesn't work.

I created an Access db with an ODBC link to a db on ORDS when the ODBC access was switched to 'on'. I then switched ORDS ODBC access to that project to 'off' tried opening my Access db again, and found that I could still log in and edit the db successfully using my credentials.

**Comment by thestoat** [comment]
I have just tried this and it worked fine. Please add me to your project so I can take a look

**Comment by MerielP** [comment]
As discussed in the meeting, I've just tried turning off ODBC access for an old project on Dev (the project id is 545837 - as far as I can tell, it's the oldest I have there). It worked there: if ODBC is off, I can't access the tables; if it's on, I can.

**Comment by thestoat** [comment]
This would suggest it might be a problem with Staging.

**Comment by thestoat** [comment]
Is this still a problem now new code has gone to staging?

**Comment by jajwilson** [comment]
I'm no longer getting this problem - hooray!
