### ISSUE TITLE
Can't update fields containing values from a linked table in the editing window

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#759]
1. Go into the 'city' table in the Mondial database in the data editing view.
2. Try to change the 'Country' column so that instead of displaying the country codes, it displays country names instead.
3. Find that whilst the cursor whirs away as though it's working on it, the process never actually completes.

This is on Staging 1.0.25 - 5451 in Chrome

**Comment by thestoat** [comment]
Apparently linked to issue 488?

**Comment by jajwilson** [comment]
Similar to #488 at any rate

**Comment by jajwilson** [comment]
Here's a screenshot...
![ordswhirryupdate](https://cloud.githubusercontent.com/assets/11886974/12843962/6f206770-cbf4-11e5-8268-e41322899aa2.png)

**Comment by jajwilson** [comment]
Issue fixed in Dev.
