### ISSUE TITLE
odbc connection details for 'main' database aren't always being displayed

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#761]
1. Set ODBC to 'on' for your project
2. Notice that the connection details for the database that should be top of the list (i.e. main...) is, for some reason, not being displayed...
   ![ordswheresmain](https://cloud.githubusercontent.com/assets/11886974/12844211/e8944bd4-cbf5-11e5-910d-117467fa7736.png)

**Comment by thestoat** [comment]
Is this the same issue as 755?

**Comment by jajwilson** [comment]
Essentially yes, although the first 'main' database is not being displayed either in the User Preferences or the Project page.

**Comment by thestoat** [comment]
Can you confirm this is a new database and this problem doesn't happen on Dev (i.e. only Staging)?

**Comment by thestoat** [comment]
I have just uploaded a new db in your project "New testing project 5th Feb, 2016", added a milestone db and then a test db. All seems fine. Can you remember exactly what you did to produce this error?

**Comment by jajwilson** [comment]
seems to work fine on Dev, although for some reason the main database is listed after the milestone and test in the Project page, rather than top of the list.

**Comment by jajwilson** [comment]
Yes, I can see your main tables in the details in Staging, but the original 'main' is still not appearing.

The problem arose after I
1. created the project (with ODBC set to 'off')
2. Created the database
3. Uploaded Mondial
4. Created a Milestone version (at first the milestone seemed to be empty - but the structure later appeared as it should do)
5. Created a test version
6. Switched ODBC access on
7. Noticed that whilst connection details were being given for Milestone and Staging, the Main version of the db was not appearing in the list

**Comment by thestoat** [comment]
Currently the list is not sorted in any way.

**Comment by thestoat** [comment]
This is rather frustrating - I followed those exact instructions and the problem did not happen for me. Just to be clear - please follow your instructions above, exactly as you have written them, and ensure the problem does indeed happen for you

**Comment by jajwilson** [comment]
Well it all seems to work fine now. Either it's an intermittent problem, or there was something else that I did last time around which I've since forgotten about. Unless you strongly disagree I shall mark the issue as closed, but we should keep an eye out for any reoccurrences.

**Comment by thestoat** [comment]
Agreed
