### ISSUE TITLE
Advice relating to WHERE statements is misleading

### ISSUE THREAD

**Issue by jajwilson** [ox-it/ords#763]
At present, when a user enters the SQL for a WHERE statement they need to enclose the field name the are referencing in double quotes (or at least they need to do this if the field name contains any upper-case characters). This is not clear from the accompanying instruction, however.

The current instruction is:
"(Optional) WHERE statements are used to specify that only records meeting certain criteria should be included. Enclose text strings in 'single quotes'. 
See the ORDS documentation or the W3Schools SQL tutorial for more about WHERE clauses."

The "Enclose text strings in 'single quotes'" instruction should be extended to include, " and field names in "double quotes"."

**Comment by MerielP** [comment]
Done. I've also added an extra sentence to the ORDS documentation clarifying this.
