### ISSUE TITLE
Primary keys not indicated in uploaded Access database to Staging

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#767]
I've just uploaded an Access database to Staging. This is one I've used many times before for testing.

When I view the database schema, the primary keys are not indicated:

![database schema - no primary keys](https://cloud.githubusercontent.com/assets/13660306/13180177/5413c02c-d71f-11e5-88b3-f566a5e18410.PNG)

If I upload the same database to App, the primary keys are there, exactly as they should be.

The problem can be seen in the database called 'Uploaded database' in the project 'Staging test' on (unsurprisingly) Staging. Dave, I've just made you a project administrator.

**Comment by thestoat** [comment]
Please append or send me the database so that I can see what is happening on upload

**Comment by MerielP** [comment]
Here you go (once again, inside a zip folder to keep Github happy):

[Bibliography.zip](https://github.com/ox-it/ords/files/145139/Bibliography.zip)

**Comment by MerielP** [comment]
As requested, here's a version of the file with the tblAuthors primary key field name in lower case.
[Bibliography_lower_case.zip](https://github.com/ox-it/ords/files/154809/Bibliography_lower_case.zip)

**Comment by thestoat** [comment]
Should be ok now

**Comment by MerielP** [comment]
Hurrah - seems to be working now. Will close this issue.
