### ISSUE TITLE
Field names containing spaces are treated differently on App and Staging

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#769]
I've just uploaded exactly the same database file to Staging and to App. The database is an Access file I've used many times for testing, and includes spaces and capital letters in some of the field names.

When the database is uploaded to App, it appears that the names are being converted to lower case, and spaces replaced with underscores:

![database schema - no spaces or capitals](https://cloud.githubusercontent.com/assets/13660306/13180821/038165d0-d722-11e5-9091-bb03c07ec3b3.PNG)

When exactly the same file is uploaded to Staging, no such changes are made (though as noted in issue #767, the primary keys are missing):

![database schema - no primary keys](https://cloud.githubusercontent.com/assets/13660306/13180858/202ffb06-d722-11e5-9dea-5e13c87bcb6b.PNG)

I am not quite sure why this conversion is happening on App, as we've been telling people since before the ORDS service went live that spaces in field names were fine (and until very recently, spaces didn't seem to be causing any problems). But if this conversion is needed for some reason, then it's problematic for it to have disappeared from Staging.

Can someone clarify what should actually be happening here?

**Comment by thestoat** [comment]
I believe initially the code had been written to remove spaces and upper casing from the table names since that was causing problems with processing the tables. That code has since been improved so that difference should dissapear once the Staging code hits app... unless you see it different on Dev?

**Comment by MerielP** [comment]
I've just checked, and Dev and Staging seem to be behaving the same way here.

When you say the code has been improved, do you mean that improvements have been made so we no longer need to removed spaces and upper case letters, and that hence this isn't actually a bug? Or are you saying this _is_ a bug, but one that should disappear of its own accord?

Unfortunately, it does look as though upper case and spaces are still causing problems. I'm wondering if the problem with primary keys not being indicated in the version uploaded to Staging (logged as issue #767) was caused by the fact that the primary key field names include capital letters, and (as noted in issue #772), ORDS doesn't seem able to handle primary keys which aren't all lower case.

**Comment by thestoat** [comment]
I have just checked dev and staging with the db and I believe things are handled correctly. Here are screen shots showing this ...

![image](https://cloud.githubusercontent.com/assets/491584/13388400/74e6dfba-deb7-11e5-9f79-31712e968dc8.png)

![image](https://cloud.githubusercontent.com/assets/491584/13388408/8697312e-deb7-11e5-84b9-5db9dbf8694a.png)

Let me know if this is not what you expect or if you don't see this...

**Comment by MerielP** [comment]
Those screenshots still show the problems logged as issue #767 - the primary key fields aren't indicated. If my hunch that this is being caused by issue #772 is correct, it may be that this bug will disappear when that one is fixed - but for the moment, it still looks to me as though there's a problem.

**Comment by thestoat** [comment]
Yes, there is a problem, but that is described in issue 767. The issue that this bug was raised to fix has now been fixed. Why have two issues open about the same problem?

**Comment by thestoat** [comment]
I'm assigning back to you because the bug this issue reports has been fixed. If there is still a problem with field names containing spaces (or capitals) then please re-raise this issue. If you see a new problem then please raise a new issue. If you are looking at the problem described in issue 767 then please report any matters arising against issue 767

**Comment by MerielP** [comment]
OK - closing this issue for now.
