### ISSUE TITLE
SQL import not working on Staging

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#770]
I've just tried uploading an SQL file to Staging, in the database 'Second upload test', in the project 'Staging test'. 

I got the messages telling me that my database had been sent to the server for processing, and that the import was successful. However, when I went and looked at the database, I found it was completely empty. There are no tables visible in either the schema designer or the table list.

The same file uploaded to App works perfectly well, so it's not the database itself causing the problem.

**Comment by thestoat** [comment]
I have tried this with a couple of files and all worked well so it must have something to do with the file you are using. Are you able to add that here or email it to me?

**Comment by MerielP** [comment]
The file I used is attached (in a zip folder, as Github will only accept certain formats):

[Club membership database - expanded.zip](https://github.com/ox-it/ords/files/145129/Club.membership.database.-.expanded.zip)

**Comment by thestoat** [comment]
The problem was spaces in the file name. Should be ok now

**Comment by MerielP** [comment]
Sorry - I'm still having the same problem as before. You can see this in the database called 'SQL upload text redux' in the project 'Staging test'.

**Comment by thestoat** [comment]
Does this happen on Dev? Because of course the fix I added went to dev and won't currently be in Staging

**Comment by MerielP** [comment]
Good point - sorry!

I've tried it on Dev, and it seems to be working fine there, so I'll close this issue.
