### ISSUE TITLE
Cannot make primary key field autoincrement

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#773]
On Staging, I have a database (called 'Uploaded database made from CSV files', in the project 'Staging test') which consists of two uploaded CSV files. 

I changed the primary key field from the ORDS-generated one to a pre-existing field (the problems I had doing this are detailed in issue #772), and then wanted to make the new primary key field into an autoincrement integer field.

ORDS let me change the data type to Integer, but when I attempted to tick the Autoincrement checkbox, I got this:

![autoincrement error message](https://cloud.githubusercontent.com/assets/13660306/13184178/500c18a4-d732-11e5-9386-7f21b14b02a2.PNG)

This is simply false: the field is not already an autoincrement, and when one views it via the editing screen, it just looks like any other Integer field.

I didn't get this problem when I tried to do the same thing with a similar file on App, but I can't say for certain whether the two cases are exactly the same.

**Comment by thestoat** [comment]
Should now be fixed

**Comment by MerielP** [comment]
Seems OK now - closing this issue.
