### ISSUE TITLE
Upload failure wipes existing tables

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#774]
In an attempt to reproduce a different bug, I've just uploaded a new CSV file to the database called 'Uploaded database made from CSV files', in the project 'Staging test' on Staging. The CSV file is one I've uploaded successfully on several other occasions.

When I went into the database page to see if it had finished uploading yet, I was somewhat disturbed to discover that the entire contents of the database had been wiped. There were two other tables in there, which have vanished completely. The database page looks as it would just after a new empty database has been created - it's inviting me to either upload a database or create one.

The email I got from ORDS said:

---

Hi Meriel Patrick

Unfortunately, the ORDS system has encountered a problem. Your database (artefact_catalogue) has not been imported. The page at https://staging.ords.ox.ac.uk/ordsProjectNode/commonProblems.jsp gives some suggestions on how to proceed if you are unsure how to fix this. The error reported was <Something bad has happened. Sorry. Best contact support.>.

**Comment by thestoat** [comment]
Can you let me know how I might go about creating this? I have tried uploading some csv files to a database and all works as expected.

**Comment by MerielP** [comment]
I've attempted to retrace my steps, and have succeeded in reproducing the bug. I suspect it may be significant that after uploading the first two files, I made some changes to them before uploading the third, so I've attempted to record what I did in as much detail as possible:
1. Upload CSV file called 'People'
2. Upload CSV file called 'Places'
3. Go into schema designer. Edit field names so they are all lower case with no spaces.
4. Change the primary key of the 'People' table to the 'id' field. Change the 'id' field into an autoincrement integer field.
5. Change the primary key of the 'Places' table to the 'place' field. (Leave the data type as text, as this field contains place names.)
6. Create a relationship between the 'place' field in the 'Places' table and the 'residence' field in the 'People' table.
7. Save changes, and exit the schema designer.
8. (At this point, I went and viewed the 'People' table to check that the relationship was working as I intended. However, I didn't actually make any changes.)
9. Upload CSV file called 'artefact_catalogue'

Both times I've done this, this caused the whole database to be wiped. The CSV files I used are attached below:

[CSV files.zip](https://github.com/ox-it/ords/files/145114/CSV.files.zip)

I've also just spotted that the error message didn't paste properly into the bug report above (part of the message that was in angle brackets has been edited out). Here's a screenshot of the email:

![error message after file upload causing database wipe](https://cloud.githubusercontent.com/assets/13660306/13294791/9092baa6-db1d-11e5-8362-57be30f2fb7c.PNG)

**Comment by thestoat** [comment]
This is why developers shouldn't test their own code. I'd never have thought of doing something like that - and I would have been too scared to try even if I had have ...

**Comment by thestoat** [comment]
Ok, looks like this problem will happen by simply moving a table in the schema designer and then saving a few times.

**Comment by thestoat** [comment]
This should now be fixed ...

**Comment by MerielP** [comment]
Seems to be working as it should now - closing this issue.
