### ISSUE TITLE
Tables not visible in database on Dev

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords#785]
To reproduce this issue, go to this database: https://dev.ords.ox.ac.uk/ordsProjectNode/database.jsp?dbProjectId=1699609&lid=1699797 

The schema designer shows four tables, but the table list is empty. Attempting to export the database results in an empty file.

**Comment by thestoat** [comment]
Please add me to the project

**Comment by MerielP** [comment]
Sorry - I thought you were already a member (I think I got confused about which project this was in). I've added you now.

**Comment by thestoat** [comment]
Same problem as earlier - you had been manually granted ownership but the db permissions weren't updated. Please try now

**Comment by MerielP** [comment]
Looks fine now - thanks.
